name: Update Landscape from LFX
description: Update the given landscape from LFx
inputs:
  project_processing:
    description: "Indicate for project processing, if they should be 'rebuild' or 'sync' ( or 'skip' to not build projects )"
    default: "sync"
  member_processing:
    description: "Indicate for member processing, if they should be 'build' or 'sync'"
    default: "build"
  configfile:
    description: "Filename for the config file ( defaults to config.yml )"
    default: "config.yml"
  logfile:
    description: "Filename for the log file ( defaults to debug.log )"
    default: "debug.log"
  datafile:
    description: "Filename for the data file ( defaults to landscape.yml )"
    default: "landscape.yml"
runs:
  using: composite
  steps:
    - name: Install cairo
      uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
      with:
        packages: libcairo2-dev pkg-config python3-dev
        version: 1.0
    - name: Checkout landscape
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7
      with:
        token: ${{ env.token }}
        repository: ${{ env.repository }}
        ref: ${{ env.ref }}
        path: landscape
    - name: Get latest tag for lfx-landscape-tools
      id: vars
      uses: oprypin/find-latest-tag@dd2729fe78b0bb55523ae2b2a310c6773a652bd1 # v1.1.2
      with:
        repository: jmertic/lfx-landscape-tools
        releases-only: true  # Only looks for tags associated with a GitHub Release
    - name: Checkout lfx-landscape-tools
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7
      with:
        token: ${{ env.token }}
        repository: jmertic/lfx-landscape-tools
        path: landscape-tools
        ref: ${{ steps.vars.outputs.tag }}
    - name: Set up Python 3.x
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.x'
    - name: Install poetry
      uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
    - name: Install dependencies
      shell: bash
      working-directory: ./landscape-tools
      run: poetry install
    - name: Build members from LFX
      if: ${{ inputs.member_processing == 'build' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run lfx_landscape -s -l debug --logfile $LOGFILE build_members  -c ../landscape/$CONFIGFILE
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
        CONFIGFILE: ${{ inputs.configfile }}
        LOGFILE: ${{ inputs.logfile }}
    - name: Sync members from LFX
      if: ${{ inputs.member_processing == 'sync' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run lfx_landscape -s -l debug --logfile $LOGFILE sync_members  -c ../landscape/$CONFIGFILE
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
        CONFIGFILE: ${{ inputs.configfile }}
        LOGFILE: ${{ inputs.logfile }}
    - name: Rebuild projects from LFX and other sources
      if: ${{ inputs.project_processing == 'rebuild' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run lfx_landscape -s -l debug --logfile $LOGFILE build_projects -c ../landscape/$CONFIGFILE
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
        CONFIGFILE: ${{ inputs.configfile }}
        LOGFILE: ${{ inputs.logfile }}
    - name: Sync projects from LFX and other sources
      if: ${{ inputs.project_processing == 'sync' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run lfx_landscape -s -l debug --logfile $LOGFILE sync_projects -c ../landscape/$CONFIGFILE
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
        CONFIGFILE: ${{ inputs.configfile }}
        LOGFILE: ${{ inputs.logfile }}
    - name: Rebuild LFEU projects from LFX and other sources
      if: ${{ inputs.project_processing == 'lfeu' }}
      working-directory: ./landscape-tools
      shell: bash
      run: poetry run lfx_landscape -s -l debug --logfile $LOGFILE build_lfeuprojects -c ../landscape/$CONFIGFILE
      env:
        GITHUB_TOKEN: ${{ env.token }}
        GH_TOKEN: ${{ env.token }}
        CONFIGFILE: ${{ inputs.configfile }}
        LOGFILE: ${{ inputs.logfile }}
    - name: Save logfiles file
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ inputs.logfile }} 
        path: ./landscape-tools/${{ inputs.logfile }}
        if-no-files-found: ignore
    - name: Validate landscape2 data
      uses: cncf/landscape2-validate-action@6381e8747c73412e638670807b402ef2b863e9f8 # v2.0.1
      with:
        target_kind: data
        target_path: ./landscape/${{ inputs.datafile }}
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@7c1d8465d1bfd7d35466d2ee82a8e460780561ae # v1.5.0
      with:
        format: "YYYY-MM-DD"
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        token: ${{ env.token }}
        branch-suffix: timestamp
        path: ./landscape
        title: "Update Landscape from LFX ${{ steps.date.outputs.time }}"
        commit-message: Update Landscape from LFX
        signoff: true
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-number != ''
      working-directory: ./landscape
      shell: bash
      run: |
        if [ "$(gh api repos/${{ env.repository }} --jq '.allow_auto_merge')" = "true" ]; then
          gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}" \
          || gh pr merge --squash "${{ steps.cpr.outputs.pull-request-number }}"
        fi
      env:
        GH_TOKEN: ${{ env.token }}
